# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\ui_FmvMultiplexer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VideoMultiplexer(object):
    def setupUi(self, VideoMultiplexer):
        VideoMultiplexer.setObjectName("VideoMultiplexer")
        VideoMultiplexer.resize(509, 550)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imgFMV/images/multiplexer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VideoMultiplexer.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(VideoMultiplexer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(VideoMultiplexer)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formWidget_4 = QtWidgets.QWidget(VideoMultiplexer)
        self.formWidget_4.setObjectName("formWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.formWidget_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ln_inputVideo = QtWidgets.QLineEdit(self.formWidget_4)
        self.ln_inputVideo.setObjectName("ln_inputVideo")
        self.horizontalLayout.addWidget(self.ln_inputVideo)
        self.pushButton = QtWidgets.QPushButton(self.formWidget_4)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/imgFMV/images/opened-folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.formWidget_4)
        self.label_2 = QtWidgets.QLabel(VideoMultiplexer)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.formWidget = QtWidgets.QWidget(VideoMultiplexer)
        self.formWidget.setObjectName("formWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.formWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ln_inputMeta = QtWidgets.QLineEdit(self.formWidget)
        self.ln_inputMeta.setObjectName("ln_inputMeta")
        self.horizontalLayout_2.addWidget(self.ln_inputMeta)
        self.pushButton_2 = QtWidgets.QPushButton(self.formWidget)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.formWidget)
        self.label_3 = QtWidgets.QLabel(VideoMultiplexer)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formWidget_3 = QtWidgets.QWidget(VideoMultiplexer)
        self.formWidget_3.setObjectName("formWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.formWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ln_outVideo = QtWidgets.QLineEdit(self.formWidget_3)
        self.ln_outVideo.setObjectName("ln_outVideo")
        self.horizontalLayout_3.addWidget(self.ln_outVideo)
        self.pushButton_3 = QtWidgets.QPushButton(self.formWidget_3)
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.formWidget_3)
        self.label_4 = QtWidgets.QLabel(VideoMultiplexer)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.formWidget_5 = QtWidgets.QWidget(VideoMultiplexer)
        self.formWidget_5.setObjectName("formWidget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.formWidget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ln_Mapping = QtWidgets.QLineEdit(self.formWidget_5)
        self.ln_Mapping.setObjectName("ln_Mapping")
        self.horizontalLayout_4.addWidget(self.ln_Mapping)
        self.pushButton_4 = QtWidgets.QPushButton(self.formWidget_5)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.formWidget_5)
        self.chx_sensor = QtWidgets.QCheckBox(VideoMultiplexer)
        self.chx_sensor.setObjectName("chx_sensor")
        self.verticalLayout.addWidget(self.chx_sensor)
        self.label_5 = QtWidgets.QLabel(VideoMultiplexer)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.formWidget_2 = QtWidgets.QWidget(VideoMultiplexer)
        self.formWidget_2.setObjectName("formWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.formWidget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ln_avg = QtWidgets.QLineEdit(self.formWidget_2)
        self.ln_avg.setObjectName("ln_avg")
        self.horizontalLayout_5.addWidget(self.ln_avg)
        self.pushButton_5 = QtWidgets.QPushButton(self.formWidget_2)
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.formWidget_2)
        self.bt_createMISB = QtWidgets.QPushButton(VideoMultiplexer)
        self.bt_createMISB.setObjectName("bt_createMISB")
        self.verticalLayout.addWidget(self.bt_createMISB)

        self.retranslateUi(VideoMultiplexer)
        self.pushButton.clicked.connect(VideoMultiplexer.OpenFile)
        self.pushButton_2.clicked.connect(VideoMultiplexer.OpenFile)
        self.pushButton_3.clicked.connect(VideoMultiplexer.SaveFile)
        self.pushButton_4.clicked.connect(VideoMultiplexer.OpenFile)
        self.pushButton_5.clicked.connect(VideoMultiplexer.OpenFile)
        self.bt_createMISB.clicked.connect(VideoMultiplexer.CreateMISB)
        QtCore.QMetaObject.connectSlotsByName(VideoMultiplexer)

    def retranslateUi(self, VideoMultiplexer):
        _translate = QtCore.QCoreApplication.translate
        VideoMultiplexer.setWindowTitle(_translate("VideoMultiplexer", "Video Multiplexer"))
        self.label.setText(_translate("VideoMultiplexer", "Input Video File (e.g video.ts)"))
        self.label_2.setText(_translate("VideoMultiplexer", "Input Metadata File (e.g video_metadata.csv)"))
        self.label_3.setText(_translate("VideoMultiplexer", "Output Video File (e.g out_video.ts)"))
        self.label_4.setText(_translate("VideoMultiplexer", "Metadata Field Mappinf File (e.g MISB_field_mapping.csv) (Optional)"))
        self.chx_sensor.setText(_translate("VideoMultiplexer", "Calculate coordinates using sensor information (Optional)"))
        self.label_5.setText(_translate("VideoMultiplexer", "Average Elevation (meters) ( Optional)"))
        self.bt_createMISB.setText(_translate("VideoMultiplexer", "Create MISB"))

from QGIS_FMV.gui import resources_rc
